### ISSUE TITLE
add collaborating projects to the about page

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#1]

**Comment by aqw** [comment]
@yarikoptic Which projects collaborate with DataLad that should be added?

**Comment by yarikoptic** [comment]
Well, depends on the notion we would like to place into "collaborate" ;-)
- if you consider "Yarik crawling and whining to the authors when something doesn't work", then OpenfMRI, CRCNS, INDI, NITRC-IR.  Even balsa (I have whined a lot but not yet resolved AFAIK so not included among our datasets)
- If you would like collaboration to be the other party actively using datalad in their work, list will be short -- specifically @satra (as a representative of nipype, heudiconv, nidm, ...) is one of the earliest adopters, and enforced datalad-goodness upon students at nipype workshop(s).  But you could probably list also Repronim project (http://repronim.org) as the collaborator since we hope to make good use of datalad
- Software projects using datalad 
  - native support in heudiconv, but hard to say "collaboration" since done by yours truly me
  - IIRC  mne-python folks use some datasets for testing

**Comment by aqw** [comment]
@yarikoptic I'm asking what your concrete suggestion is. Don't place the ambiguity on me when you were the one who created an issue with "no description provided." The use of "we" and "you" are misnomers here. I have no opinion on this, other than to close this issue.

Please clearly describe exactly what you are suggesting to be added to the About page --- in order for that page to be an accurate description of DataLad.

Otherwise this issue is best closed, as I too have innumerable of idle inklings of what could be better content-wise.

---Alex

**Comment by yarikoptic** [comment]
Ha... Sorry.. I didn't spot that original issue was mine! Thought that you want to add those collaborators somewhere... Yeah, scrape it for now I guess

**Comment by aqw** [comment]
@yarikoptic :-)
