### ISSUE TITLE
Seems to not get all the assets?

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad.org#22]
https://goo.gl/photos/aV56T9tDgb6Mbe1TA
Tried on phone and osx laptop

On my laptop ok, but it saw everything before so might be getting assets from cache?

**Comment by yarikoptic** [comment]
Seems to work now btw... Yet to check on the laptop which initially experienced an issue... Was anything done or it self healed?

**Comment by yarikoptic** [comment]
Now that people could actually see it they complement on the nice website, good job @aqw!

**Comment by yarikoptic** [comment]
Actually again doesn't render correctly on the phone - on mobile data this time

**Comment by aqw** [comment]
@yarikoptic I think these are caching issues due to how the previous web server was configured. Hard refresh worked for me.

---Alex

**Comment by aqw** [comment]
@yarikoptic Glad that you passed along other people's positive reactions to the website. First positive thing I've heard from you about the website in this entire process, or rather, not really from you, just you repeating what other people have said...

---Alex

**Comment by yarikoptic** [comment]
asked random person on the street -- worked for her on the phone!  for me on the phone it didn't, then did, then didn't again (which goes against caching hypothesis)... but ok -- seems to work now for majority of ppl

**Comment by aqw** [comment]
@yarikoptic Those problems will last for as long as your apache's cache policy was configured as, and depending on how you configured your E-Tags.

Traditionally, caching doesn't do so well across web servers, even with the same domain name. So it's curious, but the most likely explanation. I've only seen it once, and only on a computer that had only been to the original site in the last week.

If you find evidence to the contrary, please inform me. But it sounds like we have achieved a mini consensus that this is due to caching, so I am closing.

---Alex

**Comment by yarikoptic** [comment]
indeed probably some caching issues -- works fine in incognito mode... cleared data for all websites on the phone -- also worked fine... so indeed some kind of caching issue it was
